[project]
name = "projet-integration-2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requiÂ²-python = ">=3.11,<3.12"
dependencies = [
	"openai>=1.0.0",
	"rasa-sdk>=3.0.0",
	"requests>=2.31.0",
	"streamlit>=1.31.0",
]
